### PR TITLE
Fix url to open local server

### PR DESCRIPTION
**Pull request by nucliweb**
Fix url to open local server

### CODE REVIEW

**Comment by philipwalton** [comment]
Hmmm, I see there's a mistaken port, but I think your changes accidentally removed the URL path. If I remember correctly, the path is needed, right?

**Comment by nucliweb** [comment]
The server is initialized in the folder 2017-06-15, so the route is `/` instead of `/2017-06-15/`.

**Comment by nucliweb** [comment]
🤔I see that you don't need `, cd into the 2017-06-15 directory and` in the README because you are un `/2017-06-15/` folder 😜

**Comment by philipwalton** [comment]
Ahh, yes, I just tried and turns out you don't need the path. Thanks!

**Comment by nucliweb** [comment]
Btw, great talk 🤘🏼

**Pull request merged**
